name: 'Is Organization Member'
description: 'Checks if someone is a member of an organization.'
author: 'JamesSingleton'
inputs:
  organization:
    description: 'The organization name.'
    required: true
  username:
    description: 'The username you want to check belongs to the organization.'
    required: true
  token:
    description: 'GitHub access token.'
    required: true
outputs:
  result: # output will be available to future steps
    description: 'The result in either true or false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'user-check'
  color: 'gray-dark'
