name: 'Test Action'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # test action works running from the graph
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: is_organization_member
        with:
          organization: americanexpress
          username: JamesSingleton
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_member.outputs.result}}
          echo "$result"
