name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # test action works running from the graph
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: ./
        id: is_organization_member_zendesk
        with:
          organization: zendesk
          username: JamesSingleton
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_member_zendesk.outputs.result}}
          echo "$result"
      - uses: actions/checkout@v2
      - uses: ./
        id: is_organization_member_amex
        with:
          organization: americanexpress
          username: JamesSingleton
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_member_amex.outputs.result}}
          echo "$result"
